version: '3.5'

networks:
  mikartenergynet:
    driver: bridge

services:
  mssql:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - mikartenergynet
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MikartEnergy!69
      - MSSQL_PID=Express

  aspnetwebapi:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - mikartenergynet
    ports:
      - 5000:80
      - 44363:443
    depends_on:
      mssql:
        condition: service_started
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44363
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mikartenergy
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__MikartEnergyDatabase=Server=mssql;Database=MikartEnergyDB;User Id=sa;Password=MikartEnergy!69;TrustServerCertificate=True;
    volumes:
      - ~/.aspnet/https:/https:ro

  angular:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      aspnetwebapi:
        condition: service_started