version: '3.5'

services:
  mikartbackend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 5000:80
      - 44363:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mikartenergy
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https